from dataclasses import dataclass
from datetime import timedelta


@dataclass(frozen=True, slots=True)
class RateLimitPolicy:
    attempts: int
    window: timedelta


class LoginEmailRateLimit(RateLimitPolicy): ...
class LoginIPRateLimit(RateLimitPolicy): ...
class RegisterEmailRateLimit(RateLimitPolicy): ...
class RegisterIPRateLimit(RateLimitPolicy): ...
class RefreshTokenRateLimit(RateLimitPolicy): ...
class LogoutAllRateLimit(RateLimitPolicy): ...
